global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:'node-exporter:9100'

  - job_name: 'proxmox'
    static_configs:
      - targets:'192.168.217.128:8006'
    metrics_path: '/api2/json'  # Chemin de l'API
    params:
      node: 'pve'
    bearer_token: 'root@pam!adel'
    scheme: https
    insecure_skip_verify: true

