global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:['192.168.217.130:9100']

  - job_name: 'proxmox'
    static_configs:
      - targets:['192.168.217.128:8006']
    metrics_path: '/api2/json'  # Chemin de l'API
    params:
      node: ['pve']
    bearer_token: '1bfa535b-4b90-4a25-9c50-4a98daca8187'
    scheme: https
    insecure_skip_verify: true
rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
