global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'proxmox'
    static_configs:
      - targets: ['<PROXMOX_IP>:<PROXMOX_PORT>']
    metrics_path: '/api2/json'
    params:
      node: ['<NODE_NAME>']
    bearer_token: '<PROXMOX_TOKEN>'
    scheme: https
    insecure_skip_verify: true
